name: fastfoodgo
description: "A new Flutter project."
publish_to: 'none' # Không publish lên pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  http: ^1.5.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_polyline_points: ^3.1.0
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  flutter_dotenv: ^6.0.0
  google_sign_in: ^6.3.0
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.0.1
  uuid: ^4.1.0
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  http: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
